#!/bin/bash
#Vaatab kas apache2 on installitud ning annab tulemuseks kas 0 või 1
apache2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
#Kui rida annab vastuseks 0 siis ütleb, et apache2 ei ole paigaldatud ning paigaldab apache2
if [ $apache2 -eq 0 ]; then
	echo "Apache2 ei ole paigaldatud"
	apt-get install -y apache2;
#Kui rida annab vastuseks 1 siis ütleb, et apache2 on paigaldatud ning näitab apache2 staatust
elif [ $apache2 -eq 1 ]; then
	echo "Apache2 on paigaldatud"
	service apache2 status
fi
